-- =====================================================================
--  PADEL TORNEOS — Script de base de datos para Supabase
--  Ejecutar completo en: Supabase > SQL Editor > New query > Run
--  Es idempotente sobre una base vacía (usa DROP ... IF EXISTS al inicio).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. Limpieza (permite re-ejecutar el script en desarrollo)
-- ---------------------------------------------------------------------
drop trigger if exists on_auth_user_created on auth.users;

drop view if exists public.v_partidos cascade;
drop view if exists public.v_inscripciones cascade;
drop view if exists public.v_torneo_categorias cascade;
drop view if exists public.v_parejas cascade;
drop view if exists public.v_jugadores cascade;

drop table if exists public.partidos cascade;
drop table if exists public.zona_parejas cascade;
drop table if exists public.zonas cascade;
drop table if exists public.inscripciones cascade;
drop table if exists public.torneo_categorias cascade;
drop table if exists public.torneos cascade;
drop table if exists public.parejas cascade;
drop table if exists public.jugador_categoria_historial cascade;
drop table if exists public.jugadores cascade;
drop table if exists public.auditoria cascade;
drop table if exists public.canchas cascade;
drop table if exists public.sedes cascade;
drop table if exists public.categorias cascade;

drop type if exists public.rol_usuario cascade;
drop type if exists public.genero_categoria cascade;
drop type if exists public.estado_torneo cascade;
drop type if exists public.estado_torneo_categoria cascade;
drop type if exists public.estado_inscripcion cascade;
drop type if exists public.fase_partido cascade;
drop type if exists public.estado_partido cascade;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- 1. Tipos
-- ---------------------------------------------------------------------
create type public.rol_usuario             as enum ('jugador', 'editor', 'administrador');
create type public.genero_categoria        as enum ('caballeros', 'damas', 'mixto');
create type public.estado_torneo           as enum ('borrador', 'publicado', 'en_curso', 'finalizado', 'cancelado');
create type public.estado_torneo_categoria as enum ('inscripcion', 'zonas', 'playoff', 'finalizada', 'suspendida');
create type public.estado_inscripcion      as enum ('activa', 'cancelada');
create type public.fase_partido            as enum ('zona', 'dieciseisavos', 'octavos', 'cuartos', 'semifinal', 'final');
create type public.estado_partido          as enum ('pendiente', 'finalizado', 'wo', 'bye');

-- ---------------------------------------------------------------------
-- 2. Tablas
-- ---------------------------------------------------------------------
-- tipo 'nivel': 3ra..7ma (la categoría propia de cada jugador).
-- tipo 'suma' : categorías de torneo por suma de categorías de la pareja (Suma 8 .. Suma 14),
--               de caballeros, damas o mixto. El admin puede crear más desde la app.
create table public.categorias (
  id      smallint generated by default as identity (start with 10) primary key,
  nombre  text not null unique,
  genero  public.genero_categoria not null,
  tipo    text not null default 'nivel' check (tipo in ('nivel', 'suma')),
  nivel   smallint check (nivel between 1 and 9),   -- 3 = 3ra, 7 = 7ma (solo tipo nivel)
  suma    smallint check (suma between 4 and 20),    -- solo tipo suma
  activa  boolean not null default true,
  orden   smallint not null,
  constraint categorias_tipo_coherente check (
    (tipo = 'nivel' and nivel is not null and suma is null and genero <> 'mixto')
    or (tipo = 'suma' and suma is not null and nivel is null)
  ),
  constraint categorias_suma_unica unique (tipo, genero, suma)
);

insert into public.categorias (id, nombre, genero, nivel, orden) values
  (1, '3ra Caballeros', 'caballeros', 3, 1),
  (2, '4ta Caballeros', 'caballeros', 4, 2),
  (3, '5ta Caballeros', 'caballeros', 5, 3),
  (4, '6ta Caballeros', 'caballeros', 6, 4),
  (5, '7ma Caballeros', 'caballeros', 7, 5),
  (6, '4ta Damas',      'damas',      4, 6),
  (7, '5ta Damas',      'damas',      5, 7),
  (8, '6ta Damas',      'damas',      6, 8),
  (9, '7ma Damas',      'damas',      7, 9);

insert into public.categorias (nombre, genero, tipo, suma, orden)
select 'Suma ' || s || ' ' || initcap(g::text), g, 'suma', s,
       100 + (array_position(array['caballeros','damas','mixto'], g::text) - 1) * 20 + s
from generate_series(8, 14) s,
     unnest(array['caballeros','damas','mixto']::public.genero_categoria[]) g;

create table public.jugadores (
  id            uuid primary key references auth.users(id) on delete cascade,
  dni           text not null unique check (dni ~ '^[0-9]{6,9}$'),
  nombre        text not null check (length(trim(nombre)) > 0),
  apellido      text not null check (length(trim(apellido)) > 0),
  telefono      text not null check (length(trim(telefono)) >= 6),
  email         text,
  categoria_id  smallint not null references public.categorias(id),
  rol           public.rol_usuario not null default 'jugador',
  activo        boolean not null default true,
  debe_cambiar_password boolean not null default false, -- true tras un reseteo del admin
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index on public.jugadores (categoria_id);
create index on public.jugadores (apellido, nombre);

create table public.jugador_categoria_historial (
  id                     bigint generated always as identity primary key,
  jugador_id             uuid not null references public.jugadores(id) on delete cascade,
  categoria_anterior_id  smallint references public.categorias(id),
  categoria_nueva_id     smallint not null references public.categorias(id),
  cambiado_por           uuid references public.jugadores(id),
  created_at             timestamptz not null default now()
);
create index on public.jugador_categoria_historial (jugador_id, created_at desc);

create table public.sedes (
  id         uuid primary key default gen_random_uuid(),
  nombre     text not null unique,
  direccion  text,
  activa     boolean not null default true,
  created_at timestamptz not null default now()
);
insert into public.sedes (nombre, direccion) values
  ('NODO', null);

-- Canchas de cada complejo (administrables: nombre, orden, activa)
create table public.canchas (
  id         uuid primary key default gen_random_uuid(),
  sede_id    uuid not null references public.sedes(id) on delete cascade,
  nombre     text not null check (length(trim(nombre)) > 0),
  orden      smallint not null default 0,
  activa     boolean not null default true,
  created_at timestamptz not null default now(),
  constraint canchas_nombre_unico unique (sede_id, nombre)
);
insert into public.canchas (sede_id, nombre, orden)
select s.id, c.nombre, c.orden
from public.sedes s
join (values ('NODO', 'Cancha 1', 1), ('NODO', 'Cancha 2', 2), ('NODO', 'Cancha 3', 3)) c(sede, nombre, orden)
  on c.sede = s.nombre;

create table public.parejas (
  id           uuid primary key default gen_random_uuid(),
  jugador1_id  uuid not null references public.jugadores(id) on delete cascade,
  jugador2_id  uuid not null references public.jugadores(id) on delete cascade,
  activa       boolean not null default true,
  creada_por   uuid references public.jugadores(id),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  constraint parejas_orden check (jugador1_id < jugador2_id),
  constraint parejas_unicas unique (jugador1_id, jugador2_id)
);
create index on public.parejas (jugador2_id);

create table public.torneos (
  id                    uuid primary key default gen_random_uuid(),
  nombre                text not null,
  descripcion           text,
  fecha_desde           date not null,
  fecha_hasta           date not null,
  cierre_inscripcion    timestamptz not null,
  observaciones         text,
  precio_inscripcion    numeric(12,2),
  estado                public.estado_torneo not null default 'borrador',
  -- Americano: se juega en el día, a un solo set de games_set_unico games (7 o 9)
  americano             boolean not null default false,
  games_set_unico       smallint check (games_set_unico between 4 and 12),
  created_by            uuid references public.jugadores(id),
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  constraint torneos_fechas check (fecha_hasta >= fecha_desde),
  constraint torneos_americano check (
    americano = (games_set_unico is not null) and (not americano or fecha_hasta = fecha_desde)
  )
);

create table public.torneo_categorias (
  id            uuid primary key default gen_random_uuid(),
  torneo_id     uuid not null references public.torneos(id) on delete cascade,
  categoria_id  smallint not null references public.categorias(id),
  cupo_max      smallint not null default 24 check (cupo_max between 6 and 24),
  cupo_min      smallint not null default 6  check (cupo_min >= 6),
  estado        public.estado_torneo_categoria not null default 'inscripcion',
  created_at    timestamptz not null default now(),
  constraint torneo_categoria_unica unique (torneo_id, categoria_id),
  constraint torneo_categoria_cupos check (cupo_min <= cupo_max)
);

create table public.inscripciones (
  id                    uuid primary key default gen_random_uuid(),
  torneo_categoria_id   uuid not null references public.torneo_categorias(id) on delete cascade,
  pareja_id             uuid not null references public.parejas(id),
  problemas_horario     text not null default '',
  estado                public.estado_inscripcion not null default 'activa',
  pagada                boolean not null default false,
  inscripta_por         uuid references public.jugadores(id),
  cancelada_at          timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);
create unique index inscripciones_pareja_activa_unica
  on public.inscripciones (torneo_categoria_id, pareja_id) where estado = 'activa';
create index on public.inscripciones (pareja_id);

create table public.zonas (
  id                   uuid primary key default gen_random_uuid(),
  torneo_categoria_id  uuid not null references public.torneo_categorias(id) on delete cascade,
  nombre               text not null,          -- 'A', 'B', ...
  constraint zona_unica unique (torneo_categoria_id, nombre)
);

create table public.zona_parejas (
  zona_id         uuid not null references public.zonas(id) on delete cascade,
  inscripcion_id  uuid not null references public.inscripciones(id) on delete cascade,
  posicion_sorteo smallint not null,            -- 1..4 (define el cruce 1v4 / 2v3)
  primary key (zona_id, inscripcion_id),
  constraint zona_parejas_inscripcion_unica unique (inscripcion_id)
);

create table public.partidos (
  id                    uuid primary key default gen_random_uuid(),
  torneo_categoria_id   uuid not null references public.torneo_categorias(id) on delete cascade,
  fase                  public.fase_partido not null,
  zona_id               uuid references public.zonas(id) on delete cascade,
  ronda                 smallint not null default 1,
  orden                 smallint not null default 1,
  tipo_zona             text check (tipo_zona in ('ganadores', 'perdedores')),
  pareja_a_id           uuid references public.inscripciones(id),
  pareja_b_id           uuid references public.inscripciones(id),
  sede_id               uuid references public.sedes(id),
  cancha_id             uuid references public.canchas(id) on delete set null,
  fecha_hora            timestamptz,
  super_tiebreak        boolean not null default false,   -- zona: 3er set = super tiebreak a 11
  s1_a smallint, s1_b smallint,
  s2_a smallint, s2_b smallint,
  s3_a smallint, s3_b smallint,
  ganador_id            uuid references public.inscripciones(id),
  estado                public.estado_partido not null default 'pendiente',
  siguiente_partido_id  uuid references public.partidos(id) on delete set null,
  siguiente_slot        char(1) check (siguiente_slot in ('A', 'B')),
  cargado_por           uuid references public.jugadores(id),
  cargado_at            timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  constraint partidos_zona_coherente check ((fase = 'zona') = (zona_id is not null)),
  constraint partidos_parejas_distintas check (pareja_a_id is null or pareja_b_id is null or pareja_a_id <> pareja_b_id)
);
create index on public.partidos (torneo_categoria_id, fase, ronda, orden);
create index on public.partidos (zona_id);
create index on public.partidos (pareja_a_id);
create index on public.partidos (pareja_b_id);
create index on public.partidos (fecha_hora);

-- ---------------------------------------------------------------------
-- 3. Funciones auxiliares
-- ---------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

create trigger t_jugadores_touch     before update on public.jugadores     for each row execute function public.touch_updated_at();
create trigger t_parejas_touch       before update on public.parejas       for each row execute function public.touch_updated_at();
create trigger t_torneos_touch       before update on public.torneos       for each row execute function public.touch_updated_at();
create trigger t_inscripciones_touch before update on public.inscripciones for each row execute function public.touch_updated_at();
create trigger t_partidos_touch      before update on public.partidos      for each row execute function public.touch_updated_at();

create or replace function public.mi_rol()
returns public.rol_usuario language sql stable security definer set search_path = public as $$
  select rol from public.jugadores where id = auth.uid()
$$;

create or replace function public.es_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce((select rol = 'administrador' from public.jugadores where id = auth.uid()), false)
$$;

create or replace function public.es_editor_o_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce((select rol in ('editor', 'administrador') from public.jugadores where id = auth.uid()), false)
$$;

-- Llamadas desde el SQL Editor / service_role no tienen auth.uid(): se tratan como sistema.
create or replace function public.es_sistema_o_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select auth.uid() is null or public.es_admin()
$$;

create or replace function public.es_miembro_pareja(p_pareja uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.parejas
    where id = p_pareja and auth.uid() in (jugador1_id, jugador2_id)
  )
$$;

create or replace function public.es_miembro_inscripcion(p_inscripcion uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.inscripciones i
    join public.parejas p on p.id = i.pareja_id
    where i.id = p_inscripcion and auth.uid() in (p.jugador1_id, p.jugador2_id)
  )
$$;

-- ---------------------------------------------------------------------
-- 4. Regla de elegibilidad de categorías
--    * Caballeros: solo categorías de caballeros.
--    * Damas: categorías de damas o de caballeros (equivale a 2 categorías
--      por debajo: dama 5ta = caballero 7ma).
--    * Pareja: solo puede jugar en la categoría de su jugador mejor
--      categorizado o superiores (número de categoría <= mínimo del par).
-- ---------------------------------------------------------------------
create or replace function public.nivel_efectivo(p_cat_jugador smallint, p_cat_torneo smallint)
returns smallint language sql immutable set search_path = public as $$
  select case
           when t.genero = 'damas' and j.genero = 'caballeros' then null   -- no habilitado
           when t.genero = 'caballeros' and j.genero = 'damas' then (j.nivel + 2)::smallint
           else j.nivel
         end
  from public.categorias j, public.categorias t
  where j.id = p_cat_jugador and t.id = p_cat_torneo
$$;

-- Nivel: la pareja juega en la categoría de su mejor jugador o superiores.
-- Suma : la suma de categorías de la pareja tiene que ser >= la de la categoría
--        (dama en caballeros cuenta +2; mixto = una dama y un caballero, números tal cual).
create or replace function public.pareja_puede_jugar(p_pareja uuid, p_categoria smallint)
returns boolean language sql stable security definer set search_path = public as $$
  with t as (select * from public.categorias where id = p_categoria),
  js as (
    select public.nivel_efectivo(j.categoria_id, p_categoria) as n, cj.genero
    from public.parejas p
    join public.jugadores j on j.id in (p.jugador1_id, p.jugador2_id)
    join public.categorias cj on cj.id = j.categoria_id
    where p.id = p_pareja
  )
  select coalesce((
    select count(*) = 2 and bool_and(js.n is not null)
           and case when t.tipo = 'nivel' then t.nivel <= min(js.n)
                    else sum(js.n) >= t.suma
                         and (t.genero <> 'mixto' or count(distinct js.genero) = 2)
               end
    from js, t
    group by t.tipo, t.nivel, t.suma, t.genero
  ), false)
$$;

create or replace function public.categorias_habilitadas_pareja(p_pareja uuid)
returns setof smallint language sql stable security definer set search_path = public as $$
  select c.id from public.categorias c where c.activa and public.pareja_puede_jugar(p_pareja, c.id) order by c.orden
$$;

-- ---------------------------------------------------------------------
-- 5. Alta de jugadores (trigger sobre auth.users)
--    La app se registra con email sintético <dni>@jugadores.padel y
--    manda los datos en user_metadata.
-- ---------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  m jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
begin
  if m ->> 'dni' is null then
    return new;   -- usuarios creados a mano desde el dashboard: sin perfil
  end if;

  insert into public.jugadores (id, dni, nombre, apellido, telefono, email, categoria_id)
  values (
    new.id,
    trim(m ->> 'dni'),
    trim(m ->> 'nombre'),
    trim(m ->> 'apellido'),
    trim(m ->> 'telefono'),
    nullif(trim(coalesce(m ->> 'email', '')), ''),
    (m ->> 'categoria_id')::smallint
  );

  insert into public.jugador_categoria_historial (jugador_id, categoria_anterior_id, categoria_nueva_id, cambiado_por)
  values (new.id, null, (m ->> 'categoria_id')::smallint, new.id);

  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.dni_disponible(p_dni text)
returns boolean language sql stable security definer set search_path = public as $$
  select not exists (select 1 from public.jugadores where dni = trim(p_dni))
$$;

-- Protege campos que solo el administrador puede modificar
create or replace function public.jugadores_proteger()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if not public.es_sistema_o_admin() then
    if new.categoria_id is distinct from old.categoria_id then
      raise exception 'Solo el administrador puede cambiar la categoría de un jugador';
    end if;
    if new.rol is distinct from old.rol then
      raise exception 'Solo el administrador puede cambiar roles';
    end if;
    if new.dni is distinct from old.dni then
      raise exception 'El DNI no se puede modificar';
    end if;
    if new.activo is distinct from old.activo then
      raise exception 'Solo el administrador puede activar o desactivar jugadores';
    end if;
    if new.debe_cambiar_password and not old.debe_cambiar_password then
      raise exception 'Solo el administrador puede resetear contraseñas';
    end if;
  end if;

  if new.categoria_id is distinct from old.categoria_id then
    insert into public.jugador_categoria_historial (jugador_id, categoria_anterior_id, categoria_nueva_id, cambiado_por)
    values (new.id, old.categoria_id, new.categoria_id, auth.uid());
  end if;
  return new;
end $$;

create trigger t_jugadores_proteger
  before update on public.jugadores
  for each row execute function public.jugadores_proteger();

-- La categoría propia de un jugador es siempre de nivel (nunca una "Suma")
create or replace function public.jugadores_validar_categoria()
returns trigger language plpgsql set search_path = public as $$
begin
  if (select tipo from public.categorias where id = new.categoria_id) is distinct from 'nivel' then
    raise exception 'La categoría de un jugador tiene que ser de nivel (3ra a 7ma)';
  end if;
  return new;
end $$;

create trigger t_jugadores_validar_categoria
  before insert or update of categoria_id on public.jugadores
  for each row execute function public.jugadores_validar_categoria();

create or replace function public.buscar_jugador_por_dni(p_dni text)
returns table (id uuid, nombre text, apellido text, categoria_id smallint, categoria text)
language sql stable security definer set search_path = public as $$
  select j.id, j.nombre, j.apellido, j.categoria_id, c.nombre
  from public.jugadores j join public.categorias c on c.id = j.categoria_id
  where j.dni = trim(p_dni) and j.activo
$$;

-- ---------------------------------------------------------------------
-- 6. Parejas
-- ---------------------------------------------------------------------
create or replace function public.crear_pareja(p_dni_companero text)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_yo uuid := auth.uid();
  v_otro uuid;
  v_id uuid;
begin
  if v_yo is null then raise exception 'Tenés que iniciar sesión'; end if;

  select id into v_otro from public.jugadores where dni = trim(p_dni_companero) and activo;
  if v_otro is null then
    raise exception 'No existe un jugador registrado con DNI %', trim(p_dni_companero);
  end if;
  if v_otro = v_yo then
    raise exception 'No podés armar una pareja con vos mismo';
  end if;

  select id into v_id from public.parejas
  where jugador1_id = least(v_yo, v_otro) and jugador2_id = greatest(v_yo, v_otro);

  if v_id is not null then
    update public.parejas set activa = true where id = v_id;
    return v_id;
  end if;

  insert into public.parejas (jugador1_id, jugador2_id, creada_por)
  values (least(v_yo, v_otro), greatest(v_yo, v_otro), v_yo)
  returning id into v_id;
  return v_id;
end $$;

create or replace function public.parejas_proteger()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.jugador1_id is distinct from old.jugador1_id or new.jugador2_id is distinct from old.jugador2_id then
    raise exception 'No se pueden cambiar los integrantes de una pareja; creá una nueva';
  end if;
  if old.activa and not new.activa and exists (
      select 1 from public.inscripciones i
      join public.torneo_categorias tc on tc.id = i.torneo_categoria_id
      where i.pareja_id = new.id and i.estado = 'activa'
        and tc.estado not in ('finalizada', 'suspendida')) then
    raise exception 'La pareja tiene inscripciones vigentes. Cancelalas antes de darla de baja';
  end if;
  return new;
end $$;

create trigger t_parejas_proteger
  before update on public.parejas
  for each row execute function public.parejas_proteger();

-- ---------------------------------------------------------------------
-- 7. Inscripciones
-- ---------------------------------------------------------------------
create or replace function public.inscripciones_validar()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_tc public.torneo_categorias;
  v_t  public.torneos;
  v_p  public.parejas;
  v_cant int;
  v_admin boolean := public.es_sistema_o_admin();
begin
  select * into v_tc from public.torneo_categorias where id = new.torneo_categoria_id for update;
  select * into v_t  from public.torneos where id = v_tc.torneo_id;

  if tg_op = 'INSERT' then
    select * into v_p from public.parejas where id = new.pareja_id;

    if not v_admin then
      if v_t.estado <> 'publicado' then
        raise exception 'El torneo no tiene la inscripción abierta';
      end if;
      if now() >= v_t.cierre_inscripcion then
        raise exception 'La inscripción de este torneo ya cerró';
      end if;
      if not public.es_miembro_pareja(new.pareja_id) then
        raise exception 'Solo podés inscribir parejas que integrás';
      end if;
    end if;

    -- El admin puede sumar parejas hasta que se cargue el primer resultado, aunque ya haya zonas
    -- (la pareja queda "sin zona" y hay que ubicarla desde el armado de zonas).
    if v_tc.estado <> 'inscripcion' and not (
         v_admin and v_tc.estado = 'zonas' and not exists (
           select 1 from public.partidos where torneo_categoria_id = v_tc.id and estado in ('finalizado', 'wo'))) then
      raise exception 'Esta categoría ya no acepta inscripciones';
    end if;
    if not v_p.activa then
      raise exception 'La pareja no está activa';
    end if;
    if not public.pareja_puede_jugar(new.pareja_id, v_tc.categoria_id) then
      raise exception 'La pareja no puede inscribirse en %: %',
        (select nombre from public.categorias where id = v_tc.categoria_id),
        (select case when tipo = 'nivel'
                  then 'por categoría solo puede jugar en la de su mejor jugador o superiores'
                  when genero = 'mixto' then 'tiene que ser una dama y un caballero, y la suma de sus categorías llegar a ' || suma
                  when genero = 'damas' then 'tienen que ser dos damas y la suma de sus categorías llegar a ' || suma
                  else 'la suma de sus categorías tiene que llegar a ' || suma || ' (una dama suma 2 categorías más)'
                end from public.categorias where id = v_tc.categoria_id);
    end if;

    select count(*) into v_cant from public.inscripciones
    where torneo_categoria_id = new.torneo_categoria_id and estado = 'activa';
    if v_cant >= v_tc.cupo_max then
      raise exception 'La categoría alcanzó el cupo máximo de % parejas', v_tc.cupo_max;
    end if;

    if exists (
      select 1 from public.inscripciones i
      join public.parejas p on p.id = i.pareja_id
      where i.torneo_categoria_id = new.torneo_categoria_id and i.estado = 'activa'
        and (p.jugador1_id in (v_p.jugador1_id, v_p.jugador2_id) or p.jugador2_id in (v_p.jugador1_id, v_p.jugador2_id))
    ) then
      raise exception 'Uno de los jugadores ya está inscripto en esta categoría con otra pareja';
    end if;

    new.estado := 'activa';
    new.inscripta_por := coalesce(new.inscripta_por, auth.uid());
    if not v_admin then new.pagada := false; end if;
    return new;
  end if;

  -- UPDATE
  if new.torneo_categoria_id is distinct from old.torneo_categoria_id or new.pareja_id is distinct from old.pareja_id then
    raise exception 'No se puede cambiar la categoría ni la pareja de una inscripción; cancelala y creá una nueva';
  end if;

  if not v_admin then
    if new.pagada is distinct from old.pagada then
      raise exception 'Solo el administrador registra pagos';
    end if;
    if old.estado = 'cancelada' and new.estado = 'activa' then
      raise exception 'Una inscripción cancelada no se puede reactivar; volvé a inscribirte';
    end if;
    if v_tc.estado <> 'inscripcion' then
      raise exception 'La categoría ya está en juego (zonas armadas): la inscripción no se puede modificar ni cancelar';
    end if;
    if now() >= v_t.cierre_inscripcion then
      raise exception 'La inscripción cerró el %: ya no podés modificarla ni cancelarla. Si no se presentan, la inscripción se cobra igual',
        to_char(v_t.cierre_inscripcion at time zone 'America/Argentina/Buenos_Aires', 'DD/MM/YYYY HH24:MI');
    end if;
  end if;

  if new.estado = 'cancelada' and old.estado = 'activa' then
    if exists (select 1 from public.zona_parejas where inscripcion_id = new.id) then
      -- El admin puede dar de baja una pareja ya ubicada mientras no haya resultados:
      -- su zona queda incompleta (sin partidos) hasta que se rearme desde el armado de zonas.
      if v_admin and not exists (select 1 from public.partidos
                                 where torneo_categoria_id = v_tc.id and estado in ('finalizado', 'wo')) then
        perform set_config('app.interno', 'on', true);
        delete from public.partidos where zona_id in (select zona_id from public.zona_parejas where inscripcion_id = new.id);
        delete from public.zona_parejas where inscripcion_id = new.id;
        perform set_config('app.interno', 'off', true);
      else
        raise exception 'La pareja ya juega en una zona con resultados cargados: no se puede cancelar';
      end if;
    end if;
    new.cancelada_at := now();
  end if;
  return new;
end $$;

create trigger t_inscripciones_validar
  before insert or update on public.inscripciones
  for each row execute function public.inscripciones_validar();

-- ---------------------------------------------------------------------
-- 8. Resultados de partidos
-- ---------------------------------------------------------------------
create or replace function public.set_valido(a smallint, b smallint, p_super boolean)
returns boolean language sql immutable as $$
  select case
    when a is null or b is null or a < 0 or b < 0 or a = b then false
    when p_super then (greatest(a, b) = 11 and least(a, b) <= 9)
                   or (greatest(a, b) > 11 and greatest(a, b) - least(a, b) = 2)
    else (greatest(a, b) = 6 and least(a, b) <= 4)
      or (greatest(a, b) = 7 and least(a, b) in (5, 6))
  end
$$;

-- Set único (americanos): gana quien llega a p_games; el otro queda en 0..p_games-1
-- El formato de partido no puede cambiar una vez que hay resultados cargados
create or replace function public.torneos_proteger_formato()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.games_set_unico is distinct from old.games_set_unico and exists (
    select 1 from public.partidos p join public.torneo_categorias tc on tc.id = p.torneo_categoria_id
    where tc.torneo_id = new.id and p.estado in ('finalizado', 'wo')
  ) then
    raise exception 'El torneo ya tiene resultados cargados: no se puede cambiar el formato de los partidos';
  end if;
  return new;
end $$;

create trigger t_torneos_proteger_formato
  before update of americano, games_set_unico on public.torneos
  for each row execute function public.torneos_proteger_formato();

-- La cancha tiene que ser del complejo (sede) del partido
create or replace function public.partidos_cancha_de_sede()
returns trigger language plpgsql set search_path = public as $$
begin
  if new.cancha_id is not null and
     (select sede_id from public.canchas where id = new.cancha_id) is distinct from new.sede_id then
    raise exception 'La cancha elegida no pertenece a ese complejo';
  end if;
  return new;
end $$;

create trigger t_partidos_cancha_de_sede
  before insert or update of cancha_id, sede_id on public.partidos
  for each row execute function public.partidos_cancha_de_sede();

create or replace function public.set_unico_valido(a smallint, b smallint, p_games smallint)
returns boolean language sql immutable as $$
  select a is not null and b is not null and a >= 0 and b >= 0
     and greatest(a, b) = p_games and least(a, b) < p_games
$$;

create or replace function public.partidos_validar()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_admin boolean := public.es_sistema_o_admin();
  v_sets_a int := 0;
  v_sets_b int := 0;
  v_games smallint;
begin
  -- Actualizaciones internas (propagación de ganadores / byes) se saltean los permisos
  if pg_trigger_depth() > 1 or current_setting('app.interno', true) = 'on' then
    return new;
  end if;

  if not v_admin then
    -- Editor: solo carga resultados de partidos pendientes
    if not public.es_editor_o_admin() then
      raise exception 'No tenés permisos para cargar resultados';
    end if;
    if old.estado <> 'pendiente' then
      raise exception 'El partido ya tiene resultado cargado; solo el administrador puede editarlo';
    end if;
    if (new.torneo_categoria_id, new.fase, new.zona_id, new.ronda, new.orden, new.tipo_zona,
        new.pareja_a_id, new.pareja_b_id, new.sede_id, new.cancha_id, new.fecha_hora,
        new.super_tiebreak, new.siguiente_partido_id, new.siguiente_slot)
       is distinct from
       (old.torneo_categoria_id, old.fase, old.zona_id, old.ronda, old.orden, old.tipo_zona,
        old.pareja_a_id, old.pareja_b_id, old.sede_id, old.cancha_id, old.fecha_hora,
        old.super_tiebreak, old.siguiente_partido_id, old.siguiente_slot) then
      raise exception 'Como editor solo podés cargar el resultado del partido';
    end if;
  end if;

  if new.estado = 'bye' and old.estado <> 'bye' then
    raise exception 'El estado "bye" lo asigna el sistema';
  end if;

  if new.estado in ('pendiente') then
    new.s1_a := null; new.s1_b := null; new.s2_a := null; new.s2_b := null; new.s3_a := null; new.s3_b := null;
    new.ganador_id := null;
    return new;
  end if;

  if new.estado in ('finalizado', 'wo') and (new.pareja_a_id is null or new.pareja_b_id is null) then
    raise exception 'El partido todavía no tiene definidas las dos parejas';
  end if;

  if new.estado = 'wo' then
    if new.ganador_id is null or new.ganador_id not in (new.pareja_a_id, new.pareja_b_id) then
      raise exception 'Indicá qué pareja gana por W.O.';
    end if;
    new.s1_a := null; new.s1_b := null; new.s2_a := null; new.s2_b := null; new.s3_a := null; new.s3_b := null;
  elsif new.estado = 'finalizado' then
    select t.games_set_unico into v_games
    from public.torneo_categorias tc join public.torneos t on t.id = tc.torneo_id
    where tc.id = new.torneo_categoria_id;
  end if;

  if new.estado = 'finalizado' and v_games is not null then
    if not public.set_unico_valido(new.s1_a, new.s1_b, v_games) then
      raise exception 'Resultado inválido (%-%): se juega a un set de % games (ej. %-%)', new.s1_a, new.s1_b, v_games, v_games, v_games - 3;
    end if;
    if coalesce(new.s2_a, new.s2_b, new.s3_a, new.s3_b) is not null then
      raise exception 'Se juega a un solo set: dejá vacíos el 2do y 3er set';
    end if;
    new.ganador_id := case when new.s1_a > new.s1_b then new.pareja_a_id else new.pareja_b_id end;
  elsif new.estado = 'finalizado' then
    if not public.set_valido(new.s1_a, new.s1_b, false) then
      raise exception 'Set 1 inválido (%-%): los sets terminan 6-0 a 6-4, 7-5 o 7-6', new.s1_a, new.s1_b;
    end if;
    if not public.set_valido(new.s2_a, new.s2_b, false) then
      raise exception 'Set 2 inválido (%-%): los sets terminan 6-0 a 6-4, 7-5 o 7-6', new.s2_a, new.s2_b;
    end if;
    v_sets_a := (new.s1_a > new.s1_b)::int + (new.s2_a > new.s2_b)::int;
    v_sets_b := 2 - v_sets_a;

    if v_sets_a = 1 then
      if not public.set_valido(new.s3_a, new.s3_b, new.super_tiebreak) then
        if new.super_tiebreak then
          raise exception 'El 3er set es super tiebreak a 11 con diferencia de 2 (ej. 11-7, 12-10)';
        else
          raise exception 'Set 3 inválido (%-%): los sets terminan 6-0 a 6-4, 7-5 o 7-6', new.s3_a, new.s3_b;
        end if;
      end if;
      v_sets_a := v_sets_a + (new.s3_a > new.s3_b)::int;
      v_sets_b := 3 - v_sets_a;
    elsif new.s3_a is not null or new.s3_b is not null then
      raise exception 'El partido se definió en 2 sets: no corresponde cargar un 3er set';
    end if;

    new.ganador_id := case when v_sets_a > v_sets_b then new.pareja_a_id else new.pareja_b_id end;
  end if;

  new.cargado_por := auth.uid();
  new.cargado_at := now();
  return new;
end $$;

create trigger t_partidos_validar
  before update on public.partidos
  for each row execute function public.partidos_validar();

-- Ubica una pareja en un slot de otro partido, verificando que no esté jugado
create or replace function public.asignar_slot(p_partido uuid, p_slot char, p_inscripcion uuid)
returns void language plpgsql security definer set search_path = public as $$
declare
  v public.partidos;
begin
  select * into v from public.partidos where id = p_partido;
  if v.id is null then return; end if;
  if (p_slot = 'A' and v.pareja_a_id is not distinct from p_inscripcion)
     or (p_slot = 'B' and v.pareja_b_id is not distinct from p_inscripcion) then
    return;
  end if;
  if v.estado in ('finalizado', 'wo') then
    raise exception 'El partido siguiente ya tiene resultado. Anulá primero ese resultado para poder modificar este';
  end if;
  if p_slot = 'A' then
    update public.partidos set pareja_a_id = p_inscripcion where id = p_partido;
  else
    update public.partidos set pareja_b_id = p_inscripcion where id = p_partido;
  end if;
end $$;

create or replace function public.partidos_propagar()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_perdedor uuid;
  v_slot char(1);
  v_gan uuid;
  v_per uuid;
begin
  if new.ganador_id is not distinct from old.ganador_id
     and new.pareja_a_id is not distinct from old.pareja_a_id
     and new.pareja_b_id is not distinct from old.pareja_b_id then
    return new;
  end if;

  v_perdedor := case
    when new.ganador_id is null then null
    when new.ganador_id = new.pareja_a_id then new.pareja_b_id
    else new.pareja_a_id end;

  -- Zona de 4: ronda 1 alimenta "ganadores" y "perdedores"
  if new.fase = 'zona' and new.ronda = 1 and new.tipo_zona is null
     and (select count(*) from public.zona_parejas where zona_id = new.zona_id) = 4 then
    v_slot := case when new.orden = 1 then 'A' else 'B' end;
    select id into v_gan from public.partidos where zona_id = new.zona_id and tipo_zona = 'ganadores';
    select id into v_per from public.partidos where zona_id = new.zona_id and tipo_zona = 'perdedores';
    perform public.asignar_slot(v_gan, v_slot, new.ganador_id);
    perform public.asignar_slot(v_per, v_slot, v_perdedor);
  end if;

  -- Playoff: el ganador avanza
  if new.fase <> 'zona' and new.siguiente_partido_id is not null then
    perform public.asignar_slot(new.siguiente_partido_id, new.siguiente_slot, new.ganador_id);
  end if;

  -- Final
  if new.fase = 'final' then
    update public.torneo_categorias
       set estado = case when new.ganador_id is null then 'playoff'::public.estado_torneo_categoria else 'finalizada' end
     where id = new.torneo_categoria_id;
  end if;

  return new;
end $$;

create trigger t_partidos_propagar
  after update on public.partidos
  for each row execute function public.partidos_propagar();

-- ---------------------------------------------------------------------
-- 9. Posiciones de zona
--    Zona de 3: partidos ganados > dif. sets > dif. games > sorteo.
--    Zona de 4: 1° gana Ganadores, 2° pierde Ganadores, 3° gana Perdedores.
--    W.O. cuenta 2-0 en sets y 12-0 en games. Super tiebreak cuenta 1 game.
-- ---------------------------------------------------------------------
create or replace function public.posiciones_zona(p_zona uuid)
returns table (
  inscripcion_id uuid, pj int, pg int, pp int,
  sets_favor int, sets_contra int, games_favor int, games_contra int,
  posicion int
)
language sql stable security definer set search_path = public as $$
  with fmt as (
    select t.games_set_unico as g
    from public.zonas z join public.torneo_categorias tc on tc.id = z.torneo_categoria_id
    join public.torneos t on t.id = tc.torneo_id where z.id = p_zona
  ),
  lados as (
    select p.id, p.estado, p.super_tiebreak, p.ganador_id, p.tipo_zona,
           p.pareja_a_id as yo,
           array[p.s1_a, p.s2_a, p.s3_a] as mis, array[p.s1_b, p.s2_b, p.s3_b] as sus
    from public.partidos p
    where p.zona_id = p_zona and p.estado in ('finalizado', 'wo')
    union all
    select p.id, p.estado, p.super_tiebreak, p.ganador_id, p.tipo_zona,
           p.pareja_b_id,
           array[p.s1_b, p.s2_b, p.s3_b], array[p.s1_a, p.s2_a, p.s3_a]
    from public.partidos p
    where p.zona_id = p_zona and p.estado in ('finalizado', 'wo')
  ),
  por_partido as (
    select l.yo,
           (l.ganador_id = l.yo) as gane,
           case when l.estado = 'wo' then case when l.ganador_id = l.yo then (case when f.g is null then 2 else 1 end) else 0 end
                else (select count(*) filter (where u.m > u.s) from unnest(l.mis, l.sus) as u(m, s) where u.m is not null) end as sf,
           case when l.estado = 'wo' then case when l.ganador_id = l.yo then 0 else (case when f.g is null then 2 else 1 end) end
                else (select count(*) filter (where u.m < u.s) from unnest(l.mis, l.sus) as u(m, s) where u.m is not null) end as sc,
           case when l.estado = 'wo' then case when l.ganador_id = l.yo then coalesce(f.g, 12) else 0 end
                else (select coalesce(sum(case when l.super_tiebreak and u.n = 3 then (u.m > u.s)::int else u.m end), 0)
                      from unnest(l.mis, l.sus) with ordinality as u(m, s, n) where u.m is not null) end as gf,
           case when l.estado = 'wo' then case when l.ganador_id = l.yo then 0 else coalesce(f.g, 12) end
                else (select coalesce(sum(case when l.super_tiebreak and u.n = 3 then (u.s > u.m)::int else u.s end), 0)
                      from unnest(l.mis, l.sus) with ordinality as u(m, s, n) where u.m is not null) end as gc
    from lados l cross join fmt f
  ),
  totales as (
    select zp.inscripcion_id, zp.posicion_sorteo,
           count(pp.yo)::int as pj,
           count(pp.yo) filter (where pp.gane)::int as pg,
           count(pp.yo) filter (where not pp.gane)::int as pp,
           coalesce(sum(pp.sf), 0)::int as sf, coalesce(sum(pp.sc), 0)::int as sc,
           coalesce(sum(pp.gf), 0)::int as gf, coalesce(sum(pp.gc), 0)::int as gc
    from public.zona_parejas zp
    left join por_partido pp on pp.yo = zp.inscripcion_id
    where zp.zona_id = p_zona
    group by zp.inscripcion_id, zp.posicion_sorteo
  ),
  fijas as (
    select x.ins, x.pos from (
      select case when p.ganador_id = p.pareja_a_id then p.pareja_a_id else p.pareja_b_id end as ins,
             case when p.tipo_zona = 'ganadores' then 1 else 3 end as pos
      from public.partidos p
      where p.zona_id = p_zona and p.tipo_zona is not null and p.ganador_id is not null
      union all
      select case when p.ganador_id = p.pareja_a_id then p.pareja_b_id else p.pareja_a_id end,
             case when p.tipo_zona = 'ganadores' then 2 else 4 end
      from public.partidos p
      where p.zona_id = p_zona and p.tipo_zona is not null and p.ganador_id is not null
    ) x
  )
  select t.inscripcion_id, t.pj, t.pg, t.pp, t.sf, t.sc, t.gf, t.gc,
         row_number() over (
           order by coalesce(f.pos, 100), t.pg desc, (t.sf - t.sc) desc, (t.gf - t.gc) desc, t.posicion_sorteo
         )::int as posicion
  from totales t
  left join fijas f on f.ins = t.inscripcion_id
  order by posicion
$$;

-- ---------------------------------------------------------------------
-- 10. Generación de zonas
--     Por defecto arma floor(N/3) zonas: la mayoría de 3 y el resto de 4.
--     Así nunca hay más de 16 clasificados (máximo: octavos de final).
-- ---------------------------------------------------------------------
-- Crea los partidos de una zona. p_parejas en orden de posición (1..3 ó 1..4):
-- zona de 3: todos contra todos · zona de 4: 1v4 y 2v3, luego ganadores y perdedores.
create or replace function public.crear_partidos_zona(p_tc uuid, p_zona uuid, p_parejas uuid[])
returns void language plpgsql security definer set search_path = public as $$
declare s uuid[] := p_parejas;
begin
  if not public.es_sistema_o_admin() then raise exception 'Solo el administrador puede armar zonas'; end if;
  if array_length(s, 1) = 3 then
    insert into public.partidos (torneo_categoria_id, fase, zona_id, ronda, orden, pareja_a_id, pareja_b_id, super_tiebreak) values
      (p_tc, 'zona', p_zona, 1, 1, s[1], s[2], true),
      (p_tc, 'zona', p_zona, 2, 1, s[1], s[3], true),
      (p_tc, 'zona', p_zona, 3, 1, s[2], s[3], true);
  else
    insert into public.partidos (torneo_categoria_id, fase, zona_id, ronda, orden, tipo_zona, pareja_a_id, pareja_b_id, super_tiebreak) values
      (p_tc, 'zona', p_zona, 1, 1, null,         s[1], s[4], true),
      (p_tc, 'zona', p_zona, 1, 2, null,         s[2], s[3], true),
      (p_tc, 'zona', p_zona, 2, 1, 'ganadores',  null, null, true),
      (p_tc, 'zona', p_zona, 2, 2, 'perdedores', null, null, true);
  end if;
end $$;

create or replace function public.generar_zonas(
  p_torneo_categoria uuid,
  p_cantidad_zonas int default null,
  p_aleatorio boolean default true
)
returns int language plpgsql security definer set search_path = public as $$
declare
  v_tc public.torneo_categorias;
  v_n int;
  v_z int;
  v_de4 int;
  v_ins uuid[];
  v_idx int := 1;
  v_tam int;
  v_zona uuid;
  v_letras text := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  i int;
  k int;
  s uuid[];
begin
  if not public.es_sistema_o_admin() then raise exception 'Solo el administrador puede armar zonas'; end if;
  perform set_config('app.sin_auditoria', 'on', true);

  select * into v_tc from public.torneo_categorias where id = p_torneo_categoria for update;
  if v_tc.id is null then raise exception 'Categoría de torneo inexistente'; end if;
  if v_tc.estado not in ('inscripcion', 'zonas') then
    raise exception 'La categoría ya está en playoff o finalizada';
  end if;
  if exists (select 1 from public.partidos where torneo_categoria_id = p_torneo_categoria and estado in ('finalizado', 'wo')) then
    raise exception 'Ya hay resultados cargados: no se pueden regenerar las zonas';
  end if;

  select array_agg(id order by case when p_aleatorio then random() else 0 end, created_at)
    into v_ins
  from public.inscripciones
  where torneo_categoria_id = p_torneo_categoria and estado = 'activa';

  v_n := coalesce(array_length(v_ins, 1), 0);
  if v_n < v_tc.cupo_min then
    raise exception 'Hay % parejas inscriptas y el mínimo para armar la categoría es %', v_n, v_tc.cupo_min;
  end if;

  v_z := coalesce(p_cantidad_zonas, v_n / 3);
  if v_z * 3 > v_n or v_z * 4 < v_n then
    raise exception 'Con % parejas se pueden armar entre % y % zonas', v_n, ceil(v_n / 4.0)::int, v_n / 3;
  end if;
  v_de4 := v_n - 3 * v_z;

  delete from public.partidos where torneo_categoria_id = p_torneo_categoria;
  delete from public.zonas where torneo_categoria_id = p_torneo_categoria;

  for i in 1..v_z loop
    v_tam := case when i <= v_de4 then 4 else 3 end;
    insert into public.zonas (torneo_categoria_id, nombre)
    values (p_torneo_categoria, substr(v_letras, i, 1))
    returning id into v_zona;

    s := v_ins[v_idx : v_idx + v_tam - 1];
    for k in 1..v_tam loop
      insert into public.zona_parejas (zona_id, inscripcion_id, posicion_sorteo) values (v_zona, s[k], k);
    end loop;
    v_idx := v_idx + v_tam;

    perform public.crear_partidos_zona(p_torneo_categoria, v_zona, s);
  end loop;

  update public.torneo_categorias set estado = 'zonas' where id = p_torneo_categoria;
  perform public.registrar('zonas', 'Zonas generadas automáticamente: ' || public.aud_tc(p_torneo_categoria) || ' (' || v_z || ' zonas)', p_torneo_categoria);
  perform set_config('app.sin_auditoria', 'off', true);
  return v_z;
end $$;

-- Intercambia dos parejas entre zonas (útil por problemas de horario)
-- Armado manual: p_zonas = [[insc_A1, insc_A2, insc_A3], [insc_B1, ...], ...]
-- (el orden dentro de cada zona es la posición: en zonas de 4 cruza 1v4 y 2v3).
-- Tienen que estar todas las parejas activas, cada una una sola vez, en zonas de 3 o 4.
-- Si la categoría ya tenía zonas, se reemplazan conservando sede/horario de los partidos que
-- no cambian de parejas.
create or replace function public.armar_zonas_manual(p_torneo_categoria uuid, p_zonas jsonb)
returns int language plpgsql security definer set search_path = public as $$
declare
  v_tc public.torneo_categorias;
  v_letras text := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  v_z int := jsonb_array_length(p_zonas);
  v_ids uuid[];
  v_zona uuid;
  v_prog jsonb;
  i int;
  s uuid[];
begin
  if not public.es_sistema_o_admin() then raise exception 'Solo el administrador puede armar zonas'; end if;
  perform set_config('app.sin_auditoria', 'on', true);

  select * into v_tc from public.torneo_categorias where id = p_torneo_categoria for update;
  if v_tc.id is null then raise exception 'Categoría de torneo inexistente'; end if;
  if v_tc.estado not in ('inscripcion', 'zonas') then
    raise exception 'La categoría ya está en playoff o finalizada';
  end if;
  if exists (select 1 from public.partidos where torneo_categoria_id = p_torneo_categoria and estado in ('finalizado', 'wo')) then
    raise exception 'Ya hay resultados cargados: no se pueden rearmar las zonas';
  end if;
  if v_z < 1 or v_z > 26 then raise exception 'Cantidad de zonas inválida'; end if;

  for i in 0..v_z - 1 loop
    if jsonb_array_length(p_zonas -> i) not between 3 and 4 then
      raise exception 'La zona % tiene % parejas: cada zona tiene que tener 3 o 4',
        substr(v_letras, i + 1, 1), jsonb_array_length(p_zonas -> i);
    end if;
  end loop;

  select array_agg(x::uuid) into v_ids
  from jsonb_array_elements(p_zonas) z, jsonb_array_elements_text(z) x;

  if (select count(distinct u) from unnest(v_ids) u) <> array_length(v_ids, 1) then
    raise exception 'Hay una pareja repetida en más de una zona';
  end if;
  if exists (select unnest(v_ids) except
             select id from public.inscripciones where torneo_categoria_id = p_torneo_categoria and estado = 'activa') then
    raise exception 'Hay parejas que no están inscriptas (o están canceladas) en esta categoría';
  end if;
  if exists (select id from public.inscripciones where torneo_categoria_id = p_torneo_categoria and estado = 'activa'
             except select unnest(v_ids)) then
    raise exception 'Faltan parejas inscriptas por ubicar en alguna zona';
  end if;

  -- guardar la programación actual por cruce (pareja_a, pareja_b) para no perderla
  select coalesce(jsonb_agg(jsonb_build_object('a', pareja_a_id, 'b', pareja_b_id, 'z', z.nombre, 'r', p.ronda, 'o', p.orden,
                                               'sede', sede_id, 'cancha', cancha_id, 'fh', fecha_hora)), '[]')
    into v_prog
  from public.partidos p join public.zonas z on z.id = p.zona_id
  where p.torneo_categoria_id = p_torneo_categoria and (p.sede_id is not null or p.fecha_hora is not null);

  delete from public.partidos where torneo_categoria_id = p_torneo_categoria;
  delete from public.zonas where torneo_categoria_id = p_torneo_categoria;

  for i in 0..v_z - 1 loop
    insert into public.zonas (torneo_categoria_id, nombre)
    values (p_torneo_categoria, substr(v_letras, i + 1, 1)) returning id into v_zona;
    select array_agg(x::uuid order by n) into s from jsonb_array_elements_text(p_zonas -> i) with ordinality t(x, n);
    insert into public.zona_parejas (zona_id, inscripcion_id, posicion_sorteo)
    select v_zona, u, n from unnest(s) with ordinality t(u, n);
    perform public.crear_partidos_zona(p_torneo_categoria, v_zona, s);
  end loop;

  -- reponer sede/horario: mismo cruce de parejas, o mismo partido de zona de 4 (ronda 2) en la misma zona
  update public.partidos p set sede_id = (g ->> 'sede')::uuid, cancha_id = (g ->> 'cancha')::uuid, fecha_hora = (g ->> 'fh')::timestamptz
  from jsonb_array_elements(v_prog) g, public.zonas z
  where p.torneo_categoria_id = p_torneo_categoria and z.id = p.zona_id
    and ((p.pareja_a_id is not null and least(p.pareja_a_id, p.pareja_b_id) = least((g ->> 'a')::uuid, (g ->> 'b')::uuid)
          and greatest(p.pareja_a_id, p.pareja_b_id) = greatest((g ->> 'a')::uuid, (g ->> 'b')::uuid))
      or (p.pareja_a_id is null and g ->> 'a' is null and z.nombre = g ->> 'z' and p.ronda = (g ->> 'r')::int and p.orden = (g ->> 'o')::int));

  update public.torneo_categorias set estado = 'zonas' where id = p_torneo_categoria;
  perform public.registrar('zonas', 'Zonas armadas: ' || public.aud_tc(p_torneo_categoria) || ' (' || v_z || ' zonas, ' ||
    jsonb_array_length(jsonb_path_query_array(p_zonas, '$[*][*]')) || ' parejas)', p_torneo_categoria);
  perform set_config('app.sin_auditoria', 'off', true);
  return v_z;
end $$;

create or replace function public.intercambiar_parejas_zona(p_ins1 uuid, p_ins2 uuid)
returns void language plpgsql security definer set search_path = public as $$
declare
  z1 public.zona_parejas;
  z2 public.zona_parejas;
begin
  if not public.es_sistema_o_admin() then raise exception 'Solo el administrador puede mover parejas'; end if;
  perform set_config('app.sin_auditoria', 'on', true);
  select * into z1 from public.zona_parejas where inscripcion_id = p_ins1;
  select * into z2 from public.zona_parejas where inscripcion_id = p_ins2;
  if z1.zona_id is null or z2.zona_id is null then raise exception 'Ambas parejas deben estar asignadas a una zona'; end if;
  if z1.zona_id = z2.zona_id then raise exception 'Las parejas ya están en la misma zona'; end if;
  if exists (select 1 from public.partidos where zona_id in (z1.zona_id, z2.zona_id) and estado in ('finalizado', 'wo')) then
    raise exception 'Alguna de las zonas ya tiene resultados cargados';
  end if;

  delete from public.zona_parejas where inscripcion_id in (p_ins1, p_ins2);
  insert into public.zona_parejas (zona_id, inscripcion_id, posicion_sorteo) values
    (z2.zona_id, p_ins1, z2.posicion_sorteo),
    (z1.zona_id, p_ins2, z1.posicion_sorteo);

  update public.partidos set
    pareja_a_id = case pareja_a_id when p_ins1 then p_ins2 when p_ins2 then p_ins1 else pareja_a_id end,
    pareja_b_id = case pareja_b_id when p_ins1 then p_ins2 when p_ins2 then p_ins1 else pareja_b_id end
  where zona_id in (z1.zona_id, z2.zona_id);
  perform public.registrar('zonas', 'Parejas intercambiadas entre zonas: ' || coalesce(public.aud_inscripcion(p_ins1), '?') || ' ↔ ' || coalesce(public.aud_inscripcion(p_ins2), '?'));
  perform set_config('app.sin_auditoria', 'off', true);
end $$;

-- ---------------------------------------------------------------------
-- 11. Generación del playoff
--     Clasifican: zona de 3 → 1° y 2°; zona de 4 → 1°, 2° y 3°.
--     Siembra: todos los 1°, luego 2°, luego 3°. Cuadro con byes para
--     completar potencia de 2, evitando cruces de la misma zona en 1ra ronda.
-- ---------------------------------------------------------------------
create or replace function public.nombre_fase(p_tamano int)
returns public.fase_partido language sql immutable as $$
  select case p_tamano
    when 2 then 'final'::public.fase_partido
    when 4 then 'semifinal'
    when 8 then 'cuartos'
    when 16 then 'octavos'
    else 'dieciseisavos' end
$$;

create or replace function public.generar_playoff(p_torneo_categoria uuid)
returns int language plpgsql security definer set search_path = public as $$
declare
  v_tc public.torneo_categorias;
  v_q int;
  v_b int := 2;
  v_rondas int;
  v_ins uuid[];
  v_zon uuid[];
  v_seeds int[] := array[1];
  v_nuevo int[];
  v_slot_ins uuid[];
  v_slot_zon uuid[];
  v_tmp uuid;
  v_id uuid;
  v_next uuid;
  v_ids jsonb := '{}'::jsonb;
  r int; j int; k int; s int; n int;
begin
  if not public.es_sistema_o_admin() then raise exception 'Solo el administrador puede armar el playoff'; end if;
  perform set_config('app.sin_auditoria', 'on', true);

  select * into v_tc from public.torneo_categorias where id = p_torneo_categoria for update;
  if v_tc.estado not in ('zonas', 'playoff') then
    raise exception 'Primero hay que armar y jugar las zonas';
  end if;
  if exists (select 1 from public.partidos
             where torneo_categoria_id = p_torneo_categoria and fase = 'zona' and estado = 'pendiente') then
    raise exception 'Faltan resultados de zona: completalos antes de armar el playoff';
  end if;
  if exists (select 1 from public.inscripciones i
             where i.torneo_categoria_id = p_torneo_categoria and i.estado = 'activa'
               and not exists (select 1 from public.zona_parejas zp where zp.inscripcion_id = i.id)) then
    raise exception 'Hay parejas inscriptas sin zona: ubicalas en el armado de zonas antes de generar el playoff';
  end if;
  if exists (select 1 from public.zonas z
             where z.torneo_categoria_id = p_torneo_categoria
               and ((select count(*) from public.zona_parejas zp where zp.zona_id = z.id) not between 3 and 4
                    or not exists (select 1 from public.partidos x where x.zona_id = z.id))) then
    raise exception 'Hay zonas incompletas (por una baja): rearmalas antes de generar el playoff';
  end if;
  if exists (select 1 from public.partidos
             where torneo_categoria_id = p_torneo_categoria and fase <> 'zona' and estado in ('finalizado', 'wo')) then
    raise exception 'El playoff ya tiene resultados cargados: no se puede regenerar';
  end if;

  delete from public.partidos where torneo_categoria_id = p_torneo_categoria and fase <> 'zona';

  -- Clasificados ordenados por siembra
  select array_agg(c.inscripcion_id order by c.posicion, c.nombre),
         array_agg(c.zona_id        order by c.posicion, c.nombre)
    into v_ins, v_zon
  from (
    select z.id as zona_id, z.nombre, pz.inscripcion_id, pz.posicion
    from public.zonas z
    cross join lateral public.posiciones_zona(z.id) pz
    where z.torneo_categoria_id = p_torneo_categoria
      and pz.posicion <= case when (select count(*) from public.zona_parejas where zona_id = z.id) = 4 then 3 else 2 end
  ) c;

  v_q := coalesce(array_length(v_ins, 1), 0);
  if v_q < 2 then raise exception 'No hay clasificados suficientes'; end if;
  while v_b < v_q loop v_b := v_b * 2; end loop;
  v_rondas := (log(2, v_b))::int;

  -- Orden de siembra estándar: 1 vs B, 2 vs B-1, etc.
  while array_length(v_seeds, 1) < v_b loop
    n := array_length(v_seeds, 1);
    v_nuevo := '{}';
    foreach s in array v_seeds loop
      v_nuevo := v_nuevo || s || (2 * n + 1 - s);
    end loop;
    v_seeds := v_nuevo;
  end loop;

  v_slot_ins := array_fill(null::uuid, array[v_b]);
  v_slot_zon := array_fill(null::uuid, array[v_b]);
  for k in 1..v_b loop
    if v_seeds[k] <= v_q then
      v_slot_ins[k] := v_ins[v_seeds[k]];
      v_slot_zon[k] := v_zon[v_seeds[k]];
    end if;
  end loop;

  -- Evitar cruces de misma zona en primera ronda
  for j in 1..(v_b / 2) loop
    if v_slot_zon[2*j-1] is not null and v_slot_zon[2*j-1] = v_slot_zon[2*j] then
      for k in 1..(v_b / 2) loop
        if k <> j and v_slot_zon[2*k] is not null
           and v_slot_zon[2*k] <> v_slot_zon[2*j-1]
           and v_slot_zon[2*j] is distinct from v_slot_zon[2*k-1] then
          v_tmp := v_slot_ins[2*j]; v_slot_ins[2*j] := v_slot_ins[2*k]; v_slot_ins[2*k] := v_tmp;
          v_tmp := v_slot_zon[2*j]; v_slot_zon[2*j] := v_slot_zon[2*k]; v_slot_zon[2*k] := v_tmp;
          exit;
        end if;
      end loop;
    end if;
  end loop;

  -- Crear partidos desde la final hacia la primera ronda
  for r in reverse v_rondas..1 loop
    n := v_b / (2 ^ r)::int;          -- partidos en la ronda r
    for j in 1..n loop
      v_next := null;
      if r < v_rondas then
        v_next := (v_ids ->> format('%s-%s', r + 1, (j + 1) / 2))::uuid;
      end if;
      insert into public.partidos (torneo_categoria_id, fase, ronda, orden, super_tiebreak,
                                   siguiente_partido_id, siguiente_slot, pareja_a_id, pareja_b_id)
      values (p_torneo_categoria, public.nombre_fase(v_b / (2 ^ (r - 1))::int), r, j, false,
              v_next, case when v_next is null then null when j % 2 = 1 then 'A' else 'B' end,
              case when r = 1 then v_slot_ins[2*j-1] end,
              case when r = 1 then v_slot_ins[2*j] end)
      returning id into v_id;
      v_ids := v_ids || jsonb_build_object(format('%s-%s', r, j), v_id);
    end loop;
  end loop;

  -- Byes: la pareja sin rival pasa directo
  perform set_config('app.interno', 'on', true);
  for j in 1..(v_b / 2) loop
    if v_slot_ins[2*j-1] is null or v_slot_ins[2*j] is null then
      v_id := (v_ids ->> format('1-%s', j))::uuid;
      v_tmp := coalesce(v_slot_ins[2*j-1], v_slot_ins[2*j]);
      update public.partidos set estado = 'bye', ganador_id = v_tmp where id = v_id;
    end if;
  end loop;

  perform set_config('app.interno', 'off', true);
  update public.torneo_categorias set estado = 'playoff' where id = p_torneo_categoria;
  perform public.registrar('zonas', 'Playoff generado: ' || public.aud_tc(p_torneo_categoria) || ' (' || v_q || ' clasificados)', p_torneo_categoria);
  perform set_config('app.sin_auditoria', 'off', true);
  return v_q;
end $$;

-- ---------------------------------------------------------------------
-- 12. Vistas de lectura (solo datos públicos: sin DNI ni teléfono)
-- ---------------------------------------------------------------------
create view public.v_jugadores as
select j.id, j.nombre, j.apellido, (j.apellido || ', ' || j.nombre) as nombre_completo,
       j.categoria_id, c.nombre as categoria, c.genero, j.activo
from public.jugadores j
join public.categorias c on c.id = j.categoria_id;

create view public.v_parejas as
select p.id, p.activa, p.created_at,
       p.jugador1_id, j1.nombre || ' ' || j1.apellido as jugador1, c1.nombre as categoria1, j1.categoria_id as categoria1_id,
       p.jugador2_id, j2.nombre || ' ' || j2.apellido as jugador2, c2.nombre as categoria2, j2.categoria_id as categoria2_id,
       j1.apellido || ' / ' || j2.apellido as nombre_corto
from public.parejas p
join public.jugadores j1 on j1.id = p.jugador1_id join public.categorias c1 on c1.id = j1.categoria_id
join public.jugadores j2 on j2.id = p.jugador2_id join public.categorias c2 on c2.id = j2.categoria_id;

create view public.v_torneo_categorias as
-- inscriptas: solo editor/admin (null para jugadores). cupo_completo: visible para todos.
select tc.id, tc.torneo_id, tc.categoria_id, c.nombre as categoria, c.genero, c.orden,
       tc.cupo_max, tc.cupo_min, tc.estado,
       case when public.es_editor_o_admin() then n.cant end as inscriptas,
       (n.cant >= tc.cupo_max) as cupo_completo,
       c.tipo, c.suma
from public.torneo_categorias tc
join public.categorias c on c.id = tc.categoria_id
join public.torneos t on t.id = tc.torneo_id
cross join lateral (
  select count(*)::int as cant from public.inscripciones i
  where i.torneo_categoria_id = tc.id and i.estado = 'activa'
) n
where t.estado <> 'borrador' or public.es_admin();

create view public.v_inscripciones as
select i.id, i.torneo_categoria_id, tc.torneo_id, tc.categoria_id, c.nombre as categoria,
       i.pareja_id, vp.nombre_corto, vp.jugador1, vp.jugador2, vp.jugador1_id, vp.jugador2_id,
       i.estado, i.created_at
from public.inscripciones i
join public.torneo_categorias tc on tc.id = i.torneo_categoria_id
join public.categorias c on c.id = tc.categoria_id
join public.v_parejas vp on vp.id = i.pareja_id
-- Mientras la categoría está en inscripción, un jugador solo ve las inscripciones de sus parejas.
-- Con las zonas armadas las parejas ya son públicas (aparecen en zonas y partidos).
where tc.estado <> 'inscripcion'
   or public.es_editor_o_admin()
   or public.es_miembro_pareja(i.pareja_id);

create view public.v_partidos as
select p.*, tc.torneo_id, tc.categoria_id, c.nombre as categoria, t.nombre as torneo,
       z.nombre as zona, s.nombre as sede, ca.nombre as cancha,
       pa.nombre_corto as pareja_a, pa.jugador1 as pareja_a_j1, pa.jugador2 as pareja_a_j2,
       pb.nombre_corto as pareja_b, pb.jugador1 as pareja_b_j1, pb.jugador2 as pareja_b_j2,
       pa.jugador1_id as pareja_a_j1_id, pa.jugador2_id as pareja_a_j2_id,
       pb.jugador1_id as pareja_b_j1_id, pb.jugador2_id as pareja_b_j2_id,
       t.games_set_unico
from public.partidos p
join public.torneo_categorias tc on tc.id = p.torneo_categoria_id
join public.categorias c on c.id = tc.categoria_id
join public.torneos t on t.id = tc.torneo_id
left join public.zonas z on z.id = p.zona_id
left join public.canchas ca on ca.id = p.cancha_id
left join public.sedes s on s.id = p.sede_id
left join (select i.id, vp.* from public.inscripciones i join public.v_parejas vp on vp.id = i.pareja_id) pa(ins_id) on pa.ins_id = p.pareja_a_id
left join (select i.id, vp.* from public.inscripciones i join public.v_parejas vp on vp.id = i.pareja_id) pb(ins_id) on pb.ins_id = p.pareja_b_id;

-- Inscripciones propias con toda la info para "Mis Inscripciones" / "Mis Torneos"
create or replace function public.mis_inscripciones()
returns table (
  id uuid, torneo_id uuid, torneo text, fecha_desde date, fecha_hasta date, cierre_inscripcion timestamptz,
  estado_torneo public.estado_torneo, torneo_categoria_id uuid, categoria text, estado_categoria public.estado_torneo_categoria,
  pareja_id uuid, pareja text, companero text, problemas_horario text, estado public.estado_inscripcion,
  pagada boolean, created_at timestamptz, puede_editar boolean
)
language sql stable security definer set search_path = public as $$
  select i.id, t.id, t.nombre, t.fecha_desde, t.fecha_hasta, t.cierre_inscripcion,
         t.estado, tc.id, c.nombre, tc.estado,
         vp.id, vp.jugador1 || ' / ' || vp.jugador2,
         case when vp.jugador1_id = auth.uid() then vp.jugador2 else vp.jugador1 end,
         i.problemas_horario, i.estado, i.pagada, i.created_at,
         (i.estado = 'activa' and now() < t.cierre_inscripcion and tc.estado = 'inscripcion')
  from public.inscripciones i
  join public.torneo_categorias tc on tc.id = i.torneo_categoria_id
  join public.torneos t on t.id = tc.torneo_id
  join public.categorias c on c.id = tc.categoria_id
  join public.v_parejas vp on vp.id = i.pareja_id
  where auth.uid() in (vp.jugador1_id, vp.jugador2_id)
  order by t.fecha_desde desc, c.orden
$$;

-- Listado de inscriptos para el administrador (incluye teléfonos y horarios)
create or replace function public.admin_inscriptos(p_torneo_categoria uuid)
returns table (
  id uuid, pareja_id uuid, pareja text, jugador1 text, dni1 text, telefono1 text, categoria1 text,
  jugador2 text, dni2 text, telefono2 text, categoria2 text,
  problemas_horario text, estado public.estado_inscripcion, pagada boolean, created_at timestamptz, zona text
)
language plpgsql stable security definer set search_path = public as $$
begin
  if not public.es_sistema_o_admin() then raise exception 'Solo para administradores'; end if;
  return query
  select i.id, p.id, j1.apellido || ' / ' || j2.apellido,
         j1.nombre || ' ' || j1.apellido, j1.dni, j1.telefono, c1.nombre,
         j2.nombre || ' ' || j2.apellido, j2.dni, j2.telefono, c2.nombre,
         i.problemas_horario, i.estado, i.pagada, i.created_at, z.nombre
  from public.inscripciones i
  join public.parejas p on p.id = i.pareja_id
  join public.jugadores j1 on j1.id = p.jugador1_id join public.categorias c1 on c1.id = j1.categoria_id
  join public.jugadores j2 on j2.id = p.jugador2_id join public.categorias c2 on c2.id = j2.categoria_id
  left join public.zona_parejas zp on zp.inscripcion_id = i.id
  left join public.zonas z on z.id = zp.zona_id
  where i.torneo_categoria_id = p_torneo_categoria
  order by i.estado, i.created_at;
end $$;

-- ---------------------------------------------------------------------
-- 12b. Reseteo de contraseña por el administrador
-- ---------------------------------------------------------------------
-- Genera una clave temporal legible (sin 0/O, 1/l/I), la guarda hasheada con bcrypt
-- en auth.users, cierra las sesiones abiertas del jugador y lo obliga a cambiarla al entrar.
-- La clave en texto plano solo se devuelve una vez, al admin que la generó.
create or replace function public.admin_resetear_password(p_jugador uuid)
returns text language plpgsql volatile security definer set search_path = public, extensions as $$
declare
  v_alfabeto constant text := 'abcdefghjkmnpqrstuvwxyz23456789';
  v_bytes bytea := extensions.gen_random_bytes(8);
  v_pass text := '';
  i int;
begin
  if not public.es_admin() then
    raise exception 'Solo el administrador puede resetear contraseñas';
  end if;
  if p_jugador = auth.uid() then
    raise exception 'Tu propia contraseña cambiala desde Perfil';
  end if;
  if not exists (select 1 from public.jugadores where id = p_jugador) then
    raise exception 'Jugador inexistente';
  end if;

  for i in 0..7 loop
    v_pass := v_pass || substr(v_alfabeto, (get_byte(v_bytes, i) % length(v_alfabeto)) + 1, 1);
  end loop;

  update auth.users
     set encrypted_password = extensions.crypt(v_pass, extensions.gen_salt('bf')),
         updated_at = now()
   where id = p_jugador;

  delete from auth.sessions where user_id = p_jugador;  -- cierra sesiones abiertas (cascadea refresh tokens)

  update public.jugadores set debe_cambiar_password = true where id = p_jugador;
  perform public.registrar('jugador', 'Contraseña reseteada: ' ||
    (select nombre || ' ' || apellido || ' (' || dni || ')' from public.jugadores where id = p_jugador), p_jugador);
  return v_pass;
end $$;

-- El jugador la llama después de cambiar su contraseña con supabase.auth.updateUser
create or replace function public.marcar_password_cambiada()
returns void language sql volatile security definer set search_path = public as $$
  update public.jugadores set debe_cambiar_password = false where id = auth.uid()
$$;

-- ---------------------------------------------------------------------
-- 12d. Inscripción por el administrador y control al recategorizar
-- ---------------------------------------------------------------------
-- Inscribe (y si hace falta crea/reactiva) la pareja de los dos DNI. Vale aunque haya cerrado la
-- inscripción, hasta que la categoría tenga el primer resultado. Devuelve el id de la inscripción.
create or replace function public.admin_inscribir(
  p_torneo_categoria uuid, p_dni1 text, p_dni2 text, p_horario text, p_pagada boolean default false
) returns uuid language plpgsql volatile security definer set search_path = public as $$
declare
  a uuid; b uuid; v_par uuid; v_ins uuid;
begin
  if not public.es_sistema_o_admin() then raise exception 'Solo el administrador puede inscribir parejas de otros jugadores'; end if;
  select id into a from public.jugadores where dni = trim(p_dni1) and activo;
  select id into b from public.jugadores where dni = trim(p_dni2) and activo;
  if a is null then raise exception 'No hay un jugador activo con DNI %', trim(p_dni1); end if;
  if b is null then raise exception 'No hay un jugador activo con DNI %', trim(p_dni2); end if;
  if a = b then raise exception 'Los dos DNI son del mismo jugador'; end if;

  select id into v_par from public.parejas where jugador1_id = least(a, b) and jugador2_id = greatest(a, b);
  if v_par is null then
    insert into public.parejas (jugador1_id, jugador2_id, creada_por)
    values (least(a, b), greatest(a, b), auth.uid()) returning id into v_par;
  else
    update public.parejas set activa = true where id = v_par and not activa;
  end if;

  insert into public.inscripciones (torneo_categoria_id, pareja_id, problemas_horario, pagada, inscripta_por)
  values (p_torneo_categoria, v_par, coalesce(nullif(trim(p_horario), ''), 'Ninguno'), coalesce(p_pagada, false), auth.uid())
  returning id into v_ins;
  return v_ins;
end $$;

-- Inscripciones activas del jugador, todavía sin resultados, en categorías en las que su pareja
-- ya no puede jugar (por ejemplo, después de ascenderlo). Solo admin.
create or replace function public.inscripciones_no_elegibles(p_jugador uuid)
returns table (inscripcion_id uuid, torneo text, categoria text, pareja text, en_zona boolean)
language sql stable security definer set search_path = public as $$
  select i.id, t.nombre, c.nombre, vp.nombre_corto,
         exists (select 1 from public.zona_parejas zp where zp.inscripcion_id = i.id)
  from public.inscripciones i
  join public.parejas p on p.id = i.pareja_id
  join public.v_parejas vp on vp.id = p.id
  join public.torneo_categorias tc on tc.id = i.torneo_categoria_id
  join public.torneos t on t.id = tc.torneo_id
  join public.categorias c on c.id = tc.categoria_id
  where public.es_sistema_o_admin()
    and p_jugador in (p.jugador1_id, p.jugador2_id)
    and i.estado = 'activa'
    and tc.estado in ('inscripcion', 'zonas')
    and not exists (select 1 from public.partidos x where x.torneo_categoria_id = tc.id and x.estado in ('finalizado', 'wo'))
    and not public.pareja_puede_jugar(p.id, tc.categoria_id)
  order by t.fecha_desde
$$;

-- ---------------------------------------------------------------------
-- 12c. Estadísticas: participaciones e instancia máxima alcanzada
-- ---------------------------------------------------------------------
-- Una fila por jugador e inscripción en categorías ya armadas (zonas, playoff o finalizada).
-- instancia_orden: 1 campeón · 2 subcampeón · 3 final (por jugarse) · 4 semifinal · 5 cuartos
--                  6 octavos · 7 dieciseisavos · 8 zona.  en_curso = la categoría no terminó.
-- Un jugador solo puede pedir las suyas; con p_jugador null (todos) hace falta ser admin.
create or replace function public.participaciones(p_jugador uuid default null)
returns table (
  jugador_id uuid, dni text, nombre text, apellido text, companero text,
  pareja_id uuid, inscripcion_id uuid, torneo_id uuid, torneo text, fecha_desde date, americano boolean,
  categoria_id smallint, categoria text, categoria_orden smallint,
  instancia text, instancia_orden int, en_curso boolean
) language plpgsql stable security definer set search_path = public as $$
#variable_conflict use_column
begin
  if p_jugador is distinct from auth.uid() and not public.es_sistema_o_admin() then
    raise exception 'Solo el administrador puede ver las estadísticas de otros jugadores';
  end if;

  return query
  with ins as (
    select i.id as ins_id, tc.id as tc_id, tc.estado as tc_estado, t.id as t_id, t.nombre as t_nombre,
           t.fecha_desde as t_desde, t.americano as t_amer, c.id as c_id, c.nombre as c_nombre, c.orden as c_orden,
           p.id as par_id, p.jugador1_id as j1, p.jugador2_id as j2
    from public.inscripciones i
    join public.torneo_categorias tc on tc.id = i.torneo_categoria_id
    join public.torneos t on t.id = tc.torneo_id
    join public.categorias c on c.id = tc.categoria_id
    join public.parejas p on p.id = i.pareja_id
    where i.estado = 'activa' and tc.estado in ('zonas', 'playoff', 'finalizada') and t.estado <> 'cancelado'
      and (p_jugador is null or p_jugador in (p.jugador1_id, p.jugador2_id))
  ),
  inst as (
    select ins.*,
      (select case when f.estado in ('finalizado', 'wo') and f.ganador_id = ins.ins_id then 1
                   when f.estado in ('finalizado', 'wo') then 2 else 3 end
       from public.partidos f
       where f.torneo_categoria_id = ins.tc_id and f.fase = 'final' and ins.ins_id in (f.pareja_a_id, f.pareja_b_id)
       limit 1) as fin,
      (select min(array_position(array['semifinal', 'cuartos', 'octavos', 'dieciseisavos']::public.fase_partido[], x.fase))
       from public.partidos x
       where x.torneo_categoria_id = ins.tc_id and x.fase in ('semifinal', 'cuartos', 'octavos', 'dieciseisavos')
         and ins.ins_id in (x.pareja_a_id, x.pareja_b_id)) as po
    from ins
  )
  select j.id, j.dni, j.nombre, j.apellido, o.nombre || ' ' || o.apellido,
         inst.par_id, inst.ins_id, inst.t_id, inst.t_nombre, inst.t_desde, inst.t_amer,
         inst.c_id, inst.c_nombre, inst.c_orden,
         case coalesce(inst.fin, inst.po + 3, 8)
           when 1 then 'campeon' when 2 then 'subcampeon' when 3 then 'final' when 4 then 'semifinal'
           when 5 then 'cuartos' when 6 then 'octavos' when 7 then 'dieciseisavos' else 'zona' end,
         coalesce(inst.fin, inst.po + 3, 8),
         inst.tc_estado <> 'finalizada'
  from inst
  join public.jugadores j on j.id in (inst.j1, inst.j2)
  join public.jugadores o on o.id in (inst.j1, inst.j2) and o.id <> j.id
  where p_jugador is null or j.id = p_jugador;
end $$;

-- Totales para el tablero del administrador
create or replace function public.admin_kpis()
returns table (jugadores int, jugadores_activos int, parejas int, parejas_activas int, torneos int, torneos_finalizados int)
language sql stable security definer set search_path = public as $$
  select (select count(*)::int from public.jugadores),
         (select count(*)::int from public.jugadores where activo),
         (select count(*)::int from public.parejas),
         (select count(*)::int from public.parejas where activa),
         (select count(*)::int from public.torneos where estado <> 'borrador'),
         (select count(*)::int from public.torneos where estado = 'finalizado')
  where public.es_sistema_o_admin()
$$;

-- ---------------------------------------------------------------------
-- 12e. Auditoría (Logs): movimientos de administradores y editores
-- ---------------------------------------------------------------------
-- Se registra con triggers sobre las tablas y desde las funciones de armado. Solo quedan
-- los movimientos hechos por un usuario logueado con rol editor o administrador (lo que se
-- corre desde el SQL Editor o lo que el sistema propaga solo no se registra).
create table public.auditoria (
  id          bigint generated always as identity primary key,
  created_at  timestamptz not null default now(),
  usuario_id  uuid references public.jugadores(id) on delete set null,
  usuario     text not null,                 -- nombre y DNI al momento del movimiento
  rol         public.rol_usuario not null,   -- rol al momento del movimiento
  tipo        text not null,                 -- torneo · categoria · inscripcion · jugador · resultado · programacion · zonas · sede · config
  movimiento  text not null,
  entidad_id  uuid
);
create index on public.auditoria (created_at desc);
create index on public.auditoria (usuario_id);
create index on public.auditoria (tipo);

create or replace function public.registrar(p_tipo text, p_movimiento text, p_entidad uuid default null)
returns void language plpgsql volatile security definer set search_path = public as $$
declare j public.jugadores;
begin
  select * into j from public.jugadores where id = auth.uid();
  if j.id is null or j.rol not in ('editor', 'administrador') then return; end if;
  insert into public.auditoria (usuario_id, usuario, rol, tipo, movimiento, entidad_id)
  values (j.id, j.nombre || ' ' || j.apellido || ' (' || j.dni || ')', j.rol, p_tipo, p_movimiento, p_entidad);
end $$;

-- true si este cambio no hay que registrarlo: propagación automática o dentro de una función que ya registra
create or replace function public.auditoria_omitir()
returns boolean language sql stable as $$
  select pg_trigger_depth() > 1 or coalesce(current_setting('app.sin_auditoria', true), '') = 'on'
$$;

create or replace function public.aud_nombre_torneo(p uuid) returns text language sql stable security definer set search_path = public as $$
  select '"' || nombre || '"' from public.torneos where id = p
$$;
create or replace function public.aud_tc(p uuid) returns text language sql stable security definer set search_path = public as $$
  select '"' || t.nombre || '" · ' || c.nombre
  from public.torneo_categorias tc join public.torneos t on t.id = tc.torneo_id join public.categorias c on c.id = tc.categoria_id
  where tc.id = p
$$;
create or replace function public.aud_inscripcion(p uuid) returns text language sql stable security definer set search_path = public as $$
  select vp.nombre_corto from public.inscripciones i join public.v_parejas vp on vp.id = i.pareja_id where i.id = p
$$;
create or replace function public.aud_partido(p public.partidos) returns text language sql stable security definer set search_path = public as $$
  select public.aud_tc(p.torneo_categoria_id) || ' · ' ||
         case when p.fase = 'zona' then 'Zona ' || coalesce((select nombre from public.zonas where id = p.zona_id), '?')
              else initcap(p.fase::text) end || ': ' ||
         coalesce(public.aud_inscripcion(p.pareja_a_id), 'A definir') || ' vs ' || coalesce(public.aud_inscripcion(p.pareja_b_id), 'A definir')
$$;

create or replace function public.aud_torneos() returns trigger language plpgsql security definer set search_path = public as $$
declare cambios text[] := '{}';
begin
  if public.auditoria_omitir() then return null; end if;
  if tg_op = 'INSERT' then
    perform public.registrar('torneo', 'Torneo creado: "' || new.nombre || '" (' || new.estado || ')', new.id);
  elsif tg_op = 'DELETE' then
    perform public.registrar('torneo', 'Torneo eliminado: "' || old.nombre || '"', old.id);
  else
    if new.estado is distinct from old.estado then
      perform public.registrar('torneo', 'Torneo "' || new.nombre || '": ' || case new.estado
        when 'publicado' then 'publicado (inscripción abierta)'
        when 'en_curso' then 'en curso'
        when 'finalizado' then 'finalizado'
        when 'cancelado' then 'cancelado'
        else 'pasado a borrador' end, new.id);
    end if;
    if new.nombre is distinct from old.nombre then cambios := cambios || ('nombre (antes "' || old.nombre || '")'); end if;
    if (new.fecha_desde, new.fecha_hasta) is distinct from (old.fecha_desde, old.fecha_hasta) then cambios := cambios || 'fechas'::text; end if;
    if new.cierre_inscripcion is distinct from old.cierre_inscripcion then
      cambios := cambios || ('cierre de inscripción a ' || to_char(new.cierre_inscripcion at time zone 'America/Argentina/Buenos_Aires', 'DD/MM/YYYY HH24:MI'));
    end if;
    if (new.descripcion, new.observaciones) is distinct from (old.descripcion, old.observaciones) then cambios := cambios || 'descripción/observaciones'::text; end if;
    if new.precio_inscripcion is distinct from old.precio_inscripcion then cambios := cambios || 'precio'::text; end if;
    if (new.americano, new.games_set_unico) is distinct from (old.americano, old.games_set_unico) then cambios := cambios || 'formato de partido'::text; end if;
    if array_length(cambios, 1) > 0 then
      perform public.registrar('torneo', 'Torneo "' || new.nombre || '" editado: ' || array_to_string(cambios, ', '), new.id);
    end if;
  end if;
  return null;
end $$;

create or replace function public.aud_torneo_categorias() returns trigger language plpgsql security definer set search_path = public as $$
begin
  if public.auditoria_omitir() then return null; end if;
  if tg_op = 'INSERT' then
    perform public.registrar('categoria', 'Categoría agregada al torneo ' || public.aud_nombre_torneo(new.torneo_id) || ': ' ||
      (select nombre from public.categorias where id = new.categoria_id), new.id);
  elsif tg_op = 'DELETE' then
    perform public.registrar('categoria', 'Categoría quitada del torneo ' || coalesce(public.aud_nombre_torneo(old.torneo_id), '(eliminado)') || ': ' ||
      (select nombre from public.categorias where id = old.categoria_id), old.id);
  else
    if new.estado is distinct from old.estado and (new.estado in ('suspendida', 'inscripcion') or old.estado = 'suspendida') then
      perform public.registrar('categoria', public.aud_tc(new.id) || ': ' ||
        case new.estado when 'suspendida' then 'suspendida' when 'inscripcion' then 'reabierta a inscripción' else 'reactivada' end, new.id);
    end if;
    if (new.cupo_max, new.cupo_min) is distinct from (old.cupo_max, old.cupo_min) then
      perform public.registrar('categoria', public.aud_tc(new.id) || ': cupo ' || new.cupo_min || ' a ' || new.cupo_max || ' parejas', new.id);
    end if;
  end if;
  return null;
end $$;

create or replace function public.aud_inscripciones() returns trigger language plpgsql security definer set search_path = public as $$
begin
  if public.auditoria_omitir() then return null; end if;
  -- solo lo que hace el staff sobre parejas ajenas (lo que hace un jugador con su propia pareja no es "movimiento de admin")
  if tg_op = 'INSERT' then
    if not public.es_miembro_pareja(new.pareja_id) then
      perform public.registrar('inscripcion', 'Pareja inscripta: ' || public.aud_inscripcion(new.id) || ' en ' || public.aud_tc(new.torneo_categoria_id), new.id);
    end if;
  else
    if new.estado = 'cancelada' and old.estado = 'activa' and not public.es_miembro_pareja(new.pareja_id) then
      perform public.registrar('inscripcion', 'Inscripción cancelada: ' || public.aud_inscripcion(new.id) || ' en ' || public.aud_tc(new.torneo_categoria_id), new.id);
    end if;
    if new.pagada is distinct from old.pagada then
      perform public.registrar('inscripcion', 'Inscripción ' || case when new.pagada then 'marcada como pagada' else 'marcada como no pagada' end || ': ' ||
        public.aud_inscripcion(new.id) || ' en ' || public.aud_tc(new.torneo_categoria_id), new.id);
    end if;
    if new.problemas_horario is distinct from old.problemas_horario and not public.es_miembro_pareja(new.pareja_id) then
      perform public.registrar('inscripcion', 'Problemas de horario editados: ' || public.aud_inscripcion(new.id) || ' en ' || public.aud_tc(new.torneo_categoria_id), new.id);
    end if;
  end if;
  return null;
end $$;

create or replace function public.aud_jugadores() returns trigger language plpgsql security definer set search_path = public as $$
declare quien text := new.nombre || ' ' || new.apellido || ' (' || new.dni || ')';
begin
  if public.auditoria_omitir() or new.id = auth.uid() and new.rol = old.rol and new.categoria_id = old.categoria_id then return null; end if;
  if new.categoria_id is distinct from old.categoria_id then
    perform public.registrar('jugador', 'Cambio de categoría: ' || quien || ' de ' ||
      (select nombre from public.categorias where id = old.categoria_id) || ' a ' || (select nombre from public.categorias where id = new.categoria_id), new.id);
  end if;
  if new.rol is distinct from old.rol then
    perform public.registrar('jugador', 'Cambio de rol: ' || quien || ' de ' || initcap(old.rol::text) || ' a ' || initcap(new.rol::text), new.id);
  end if;
  if new.activo is distinct from old.activo then
    perform public.registrar('jugador', 'Jugador ' || case when new.activo then 'activado' else 'desactivado' end || ': ' || quien, new.id);
  end if;
  if (new.nombre, new.apellido, new.telefono, new.email) is distinct from (old.nombre, old.apellido, old.telefono, old.email) and new.id <> auth.uid() then
    perform public.registrar('jugador', 'Datos editados: ' || quien, new.id);
  end if;
  return null;
end $$;

create or replace function public.aud_partidos() returns trigger language plpgsql security definer set search_path = public as $$
declare
  res text;
  g text;
begin
  if public.auditoria_omitir() then return null; end if;
  g := coalesce(public.aud_inscripcion(new.ganador_id), '?');
  res := case new.estado
    when 'wo' then 'W.O. a favor de ' || g
    else concat_ws(' ', new.s1_a || '-' || new.s1_b, new.s2_a || '-' || new.s2_b, new.s3_a || '-' || new.s3_b) || ' (gana ' || g || ')' end;
  if new.estado in ('finalizado', 'wo') and old.estado = 'pendiente' then
    perform public.registrar('resultado', 'Resultado cargado: ' || public.aud_partido(new) || ' → ' || res, new.id);
  elsif new.estado in ('finalizado', 'wo') and (new.estado, new.s1_a, new.s1_b, new.s2_a, new.s2_b, new.s3_a, new.s3_b, new.ganador_id)
        is distinct from (old.estado, old.s1_a, old.s1_b, old.s2_a, old.s2_b, old.s3_a, old.s3_b, old.ganador_id) then
    perform public.registrar('resultado', 'Resultado editado: ' || public.aud_partido(new) || ' → ' || res, new.id);
  elsif new.estado = 'pendiente' and old.estado in ('finalizado', 'wo') then
    perform public.registrar('resultado', 'Resultado anulado: ' || public.aud_partido(new), new.id);
  end if;
  if (new.sede_id, new.cancha_id, new.fecha_hora) is distinct from (old.sede_id, old.cancha_id, old.fecha_hora) then
    perform public.registrar('programacion', 'Partido programado: ' || public.aud_partido(new) || ' → ' ||
      coalesce((select nombre from public.sedes where id = new.sede_id), 'sin sede') ||
      coalesce(' · ' || (select nombre from public.canchas where id = new.cancha_id), '') ||
      coalesce(' · ' || to_char(new.fecha_hora at time zone 'America/Argentina/Buenos_Aires', 'DD/MM HH24:MI'), ' · sin horario'), new.id);
  end if;
  return null;
end $$;

create or replace function public.aud_sedes() returns trigger language plpgsql security definer set search_path = public as $$
begin
  if public.auditoria_omitir() then return null; end if;
  if tg_op = 'INSERT' then perform public.registrar('sede', 'Sede creada: ' || new.nombre, new.id);
  elsif new.activa is distinct from old.activa then perform public.registrar('sede', 'Sede ' || case when new.activa then 'activada' else 'desactivada' end || ': ' || new.nombre, new.id);
  elsif (new.nombre, new.direccion) is distinct from (old.nombre, old.direccion) then perform public.registrar('sede', 'Sede editada: ' || new.nombre, new.id);
  end if;
  return null;
end $$;

create or replace function public.aud_canchas() returns trigger language plpgsql security definer set search_path = public as $$
declare s text;
begin
  if public.auditoria_omitir() then return null; end if;
  select nombre into s from public.sedes where id = coalesce(new.sede_id, old.sede_id);
  if tg_op = 'INSERT' then perform public.registrar('sede', 'Cancha agregada en ' || s || ': ' || new.nombre, new.id);
  elsif tg_op = 'DELETE' then perform public.registrar('sede', 'Cancha eliminada en ' || s || ': ' || old.nombre, old.id);
  elsif new.nombre is distinct from old.nombre then perform public.registrar('sede', 'Cancha renombrada en ' || s || ': ' || old.nombre || ' → ' || new.nombre, new.id);
  elsif new.activa is distinct from old.activa then perform public.registrar('sede', 'Cancha ' || case when new.activa then 'activada' else 'desactivada' end || ' en ' || s || ': ' || new.nombre, new.id);
  end if;
  return null;
end $$;

create or replace function public.aud_categorias() returns trigger language plpgsql security definer set search_path = public as $$
begin
  if public.auditoria_omitir() then return null; end if;
  if tg_op = 'INSERT' then perform public.registrar('config', 'Categoría creada: ' || new.nombre);
  elsif new.activa is distinct from old.activa then perform public.registrar('config', 'Categoría ' || case when new.activa then 'activada' else 'desactivada' end || ': ' || new.nombre);
  end if;
  return null;
end $$;

create trigger t_aud_torneos after insert or update or delete on public.torneos for each row execute function public.aud_torneos();
create trigger t_aud_torneo_categorias after insert or update or delete on public.torneo_categorias for each row execute function public.aud_torneo_categorias();
create trigger t_aud_inscripciones after insert or update on public.inscripciones for each row execute function public.aud_inscripciones();
create trigger t_aud_jugadores after update on public.jugadores for each row execute function public.aud_jugadores();
create trigger t_aud_partidos after update on public.partidos for each row execute function public.aud_partidos();
create trigger t_aud_sedes after insert or update on public.sedes for each row execute function public.aud_sedes();
create trigger t_aud_canchas after insert or update or delete on public.canchas for each row execute function public.aud_canchas();
create trigger t_aud_categorias after insert or update on public.categorias for each row execute function public.aud_categorias();

-- Usuarios que tienen movimientos (para el filtro de la pantalla de Logs)
create or replace function public.auditoria_usuarios()
returns table (usuario_id uuid, usuario text)
language sql stable security definer set search_path = public as $$
  select distinct on (a.usuario_id) a.usuario_id, a.usuario
  from public.auditoria a where public.es_admin() and a.usuario_id is not null
  order by a.usuario_id, a.created_at desc
$$;

-- ---------------------------------------------------------------------
-- 13. Row Level Security
-- ---------------------------------------------------------------------
alter table public.categorias                  enable row level security;
alter table public.jugadores                   enable row level security;
alter table public.jugador_categoria_historial enable row level security;
alter table public.sedes                       enable row level security;
alter table public.canchas                     enable row level security;
alter table public.auditoria                   enable row level security;
alter table public.parejas                     enable row level security;
alter table public.torneos                     enable row level security;
alter table public.torneo_categorias           enable row level security;
alter table public.inscripciones               enable row level security;
alter table public.zonas                       enable row level security;
alter table public.zona_parejas                enable row level security;
alter table public.partidos                    enable row level security;

-- categorias: lectura pública (se usa en el registro)
create policy categorias_select on public.categorias for select using (true);
create policy categorias_admin_ins on public.categorias for insert to authenticated with check (public.es_admin());
create policy categorias_admin_upd on public.categorias for update to authenticated using (public.es_admin()) with check (public.es_admin());

-- jugadores
create policy jugadores_select on public.jugadores for select to authenticated
  using (id = auth.uid() or public.es_admin());
create policy jugadores_update on public.jugadores for update to authenticated
  using (id = auth.uid() or public.es_admin()) with check (id = auth.uid() or public.es_admin());

-- historial
create policy historial_select on public.jugador_categoria_historial for select to authenticated
  using (jugador_id = auth.uid() or public.es_admin());

-- sedes
create policy sedes_select on public.sedes for select to authenticated using (true);
create policy sedes_admin  on public.sedes for all to authenticated using (public.es_admin()) with check (public.es_admin());
create policy canchas_select on public.canchas for select to authenticated using (true);
create policy auditoria_select on public.auditoria for select to authenticated using (public.es_admin());
create policy canchas_admin  on public.canchas for all to authenticated using (public.es_admin()) with check (public.es_admin());

-- parejas (el alta es solo por la función crear_pareja)
create policy parejas_select on public.parejas for select to authenticated
  using (auth.uid() in (jugador1_id, jugador2_id) or public.es_admin());
create policy parejas_update on public.parejas for update to authenticated
  using (auth.uid() in (jugador1_id, jugador2_id) or public.es_admin())
  with check (auth.uid() in (jugador1_id, jugador2_id) or public.es_admin());

-- torneos
create policy torneos_select on public.torneos for select to authenticated
  using (estado <> 'borrador' or public.es_admin());
create policy torneos_admin on public.torneos for all to authenticated
  using (public.es_admin()) with check (public.es_admin());

-- torneo_categorias
create policy tc_select on public.torneo_categorias for select to authenticated using (true);
create policy tc_admin  on public.torneo_categorias for all to authenticated
  using (public.es_admin()) with check (public.es_admin());

-- inscripciones
create policy inscripciones_select on public.inscripciones for select to authenticated
  using (public.es_miembro_pareja(pareja_id) or public.es_admin());
create policy inscripciones_insert on public.inscripciones for insert to authenticated
  with check (public.es_miembro_pareja(pareja_id) or public.es_admin());
create policy inscripciones_update on public.inscripciones for update to authenticated
  using (public.es_miembro_pareja(pareja_id) or public.es_admin())
  with check (public.es_miembro_pareja(pareja_id) or public.es_admin());
create policy inscripciones_delete on public.inscripciones for delete to authenticated
  using (public.es_admin());

-- zonas
create policy zonas_select on public.zonas for select to authenticated using (true);
create policy zonas_admin  on public.zonas for all to authenticated using (public.es_admin()) with check (public.es_admin());
create policy zp_select    on public.zona_parejas for select to authenticated using (true);
create policy zp_admin     on public.zona_parejas for all to authenticated using (public.es_admin()) with check (public.es_admin());

-- partidos
create policy partidos_select on public.partidos for select to authenticated using (true);
create policy partidos_update on public.partidos for update to authenticated
  using (public.es_editor_o_admin()) with check (public.es_editor_o_admin());
create policy partidos_insert on public.partidos for insert to authenticated with check (public.es_admin());
create policy partidos_delete on public.partidos for delete to authenticated using (public.es_admin());

-- ---------------------------------------------------------------------
-- 14. Permisos
-- ---------------------------------------------------------------------
revoke all on public.v_jugadores, public.v_parejas, public.v_torneo_categorias,
              public.v_inscripciones, public.v_partidos from anon;
grant select on public.v_jugadores, public.v_parejas, public.v_torneo_categorias,
                public.v_inscripciones, public.v_partidos to authenticated;

revoke execute on all functions in schema public from anon;
grant execute on function public.dni_disponible(text) to anon, authenticated;
grant execute on all functions in schema public to authenticated;
-- La auditoría solo se escribe desde triggers y funciones del sistema
revoke insert, update, delete on public.auditoria from anon, authenticated;
revoke execute on function public.registrar(text, text, uuid) from anon, authenticated, public;

-- ---------------------------------------------------------------------
-- 15. Primer administrador
--     1) Registrate desde la app con tu DNI.
--     2) Ejecutá (reemplazando el DNI):
--        update public.jugadores set rol = 'administrador' where dni = '30111222';
-- ---------------------------------------------------------------------
